// Code generated by coz. DO NOT EDIT.
/**
 * Chart for the-components
 * @module the-chart
 */
'use strict'

import TheChart from './TheChart'
import TheChartStyle from './TheChartStyle'

export {
  TheChart,
  TheChartStyle,
}

