// Code generated by coz. DO NOT EDIT.
/**
 * Chart for the-components
 * @module the-chart
 * @version 1.0.2
 */
'use strict'

import TheChart from './TheChart'
import TheChartStyle from './TheChartStyle'

export default TheChat

export {
  TheChart,
  TheChartStyle
}
